部署命令

diff --git a/doc/deploy/restartJp b/doc/deploy/restartJp
--- a/doc/deploy/restartJp
+++ b/doc/deploy/restartJp
@@ -1,36 +1,14 @@
 #!/bin/bash
 source /etc/profile
+if [ '' = ${JAVA_HOME} ];then
+    echo 'Error : JAVA_HOME is need !'
+else
 
-
-
-
-    if [ '' = ${JAVA_HOME} ];then
-        echo 'Error : JAVA_HOME is need !'
-    else
-        pi=`${JAVA_HOME}/bin/jps -l | grep $1 | awk '{print $1}'`
-        if  [ -n "${pi}" ] ; then
-            while [[ $q != 'y' && $q != 'n' ]]; do
-                echo " *** want to stop progress ${1} ? y/n"
-                read q
-            done
-            if [[ $q = 'y' ]];then
-            
-                echo "<<<<==== kill progress $1 with pid ${pi}"
-
-                kill -9 ${pi}
-
-                kill -9 ${pi}
-            fi
-
-        fi
-        while [[ $q != 'y' && $q != 'n' ]]; do
-            echo " *** want to start progress ${1} ? y/n"
-            read q
-        done
-        if [[ $q = 'y' ]];then
-            `nohup ${JAVA_HOME}/bin/java -jar /usr/local/src/${1} --spring.profiles.active=${2} -Xms64m -Xmx128m -Xmn48m>/usr/local/src/${1}.out 2>&1 &`
-            echo "====>>>> start progress $1 with pid ":`${JAVA_HOME}/bin/jps -l | grep $1  | awk '{print $1}'`
-        fi
+    /usr/local/src/stopJp ${1}
+    if [ $? = 1 ];then
+        /usr/local/src/startJp ${1} ${2}
     fi
+
+fi
 
 
